name: rock_paper_scissors
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/pngs/app-icon.png"
  image_path_ios: "assets/pngs/app-icon.jpg"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/pngs/app-icon.png"
  windows:
    generate: true
    image_path: "assets/pngs/app-icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/pngs/app-icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/pngs/
    - assets/svgs/

  fonts:
    - family: Barlow
      fonts:
        - asset: assets/font/Barlow-Black.ttf
        - asset: assets/font/Barlow-BlackItalic.ttf
        - asset: assets/font/Barlow-Bold.ttf
        - asset: assets/font/Barlow-BoldItalic.ttf
        - asset: assets/font/Barlow-ExtraBold.ttf
        - asset: assets/font/Barlow-ExtraBoldItalic.ttf
        - asset: assets/font/Barlow-ExtraLight.ttf
        - asset: assets/font/Barlow-ExtraLightItalic.ttf
        - asset: assets/font/Barlow-Italic.ttf
        - asset: assets/font/Barlow-Light.ttf
        - asset: assets/font/Barlow-LightItalic.ttf
        - asset: assets/font/Barlow-Medium.ttf
        - asset: assets/font/Barlow-MediumItalic.ttf
        - asset: assets/font/Barlow-Regular.ttf
        - asset: assets/font/Barlow-SemiBold.ttf
        - asset: assets/font/Barlow-SemiBoldItalic.ttf
        - asset: assets/font/Barlow-Thin.ttf
        - asset: assets/font/Barlow-ThinItalic.ttf

